emoji:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emoticons
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      accessKeyId: xxxxxx
      accessKeySecret: xxxxxx
      bucketName: xxxxxx
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  elasticsearch:
    host: localhost
    port: 9200
  task:
    command: python
    script-path: D:\update_emoji_similarities\main.py
